version: '3'
services:
  mongodb:
    container_name: hivent-resources
    image: mongo:4.0.3
    volumes:
      - mongodata:/data/hivent-resources
    ports:
      - "27020:27017"
volumes:
    mongodata: